version: "2"
services:

  ipfs_host:
    container_name: ipfs_host
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    volumes:
      - ./.ipfs:/data/ipfs
      - ./.ipfs-export:/export
    ports:
      - "5001:5001"
      - "4001:4001"
      - "9090:8080"
      - "9091:8081"
    networks:
      main:
        aliases:
          - ipfs_host

networks:
  main: