module.exports = [
    'The Langham',
    'The Greenwich Hotel',
    'Four Seasons Resort',
    'The Jefferson',
    'Montage Kapalua Bay',
    'The Lodge at Sea Island',
    'The Peninsula',
    'Mandarin Oriental',
    'Acqualina Resort',
    'The Hay-Adams',
    'Primland',
    'Montage Deer Valley',
    'Rancho Valencia Resort & Spa',
    'The Peninsula Beverly Hills',
    'Four Seasons Resort Lanai',
    'Jade Mountain',
    'Mandarin Oriental',
    'Hospitable Hotel',
    'Cape Grace',
    'Coast Hotels',
    'The Sebastian Vail',
    'Alaska Island Resort',
    'Southern Hospitality',
    'Candlewood Suites',
    'Eagles Watch Resort',
    'Blooming Bed And Breakfast',
    'Hilltop Heaven Resort',
    'The River Front Resort',
    'Vision Resort',
    'Wonder Hill Inn',
    'Welcome Stay',
    'The Paradise Inn',
    'The Harbor Hotel',
    'The Enchanted Garden',
    'Southern Ocean Lodge',
    'Roadside Motel',
    'Hotel Lemonade',
    'Knights Inn',
    'Four Seasons Resort',
    'Astro Resort',
    'Invitation Inn',
    'Sunrise Bed And Breakfast',
    'The White Rock Hotel',
    'Hotel Mastic Marvell',
    'The Welcome Mat',
    'Count on us',
    'Always Available',
    'Feel At Home Team',
    'Priority Hospitality',
    'Southern Grace',
    'HomeTown Partners',
    '6-Star Food Service',
    'Sea Side Den',
    'The Greet Team',
    'Country Charm',
    'North Side Cafe',
    'Cordial Hosts',
    'Jupiter Guests',
    'Platinum Food team',
];
