module.exports = [
    'HUB International Ltd.',
    'Lockton Companies',
    'USI Insurance Services',
    'Alliant Insurance Services Inc.',
    'AssuredPartners Inc.',
    'Acrisure LLC',
    'BroadStreet Partners Inc.',
    'Confie',
    'EPIC',
    'NFP',
    'Risk Strategies',
    'Leavitt Group',
    'Insurance Office of America Inc.',
    'IMA Financial Group Inc.',
    'Higginbotham',
    'Cross Insurance',
    'PayneWest Insurance Inc.',
    'Woodruff Sawyer',
    'Heffernan Insurance Brokers',
    'Hylant',
    'Hilb Group',
    'AIS Insurance*',
    'INSURICA Inc.',
    'Eastern Insurance Group LLC**',
    'Prime Risk Partners Inc.',
    'Alera Group',
    'TWFG Insurance Services',
    'Assurance',
    'Propel Insurance',
    'Westwood Insurance Agency*',
    'UniVista Insurance',
    'Marshall & Sterling Enterprises Inc.',
    'Baldwin Risk Partners',
    'TrueNorth',
    'Towne Insurance',
    'Lawley Insurance',
    'Starkweather & Shepley Insurance Brokerage Inc.',
    'Professional Insurance Associates',
    'Graham Company',
    'Relation Insurance Inc.',
    'The Horton Group Inc.',
    'Houchens Insurance Group Inc.',
    'Shepherd Insurance',
    'Bowen, Miclette & Britt Insurance Agency LLC',
    'Sunstar Insurance Group',
    'LMC Insurance & Risk Management Inc.',
    'Parker, Smith & Feek Inc.',
    'Scott Insurance (James A. Scott and Son Inc.)',
    'Ansay & Associates',
    'Gowrie Group',
    'ABD Insurance and Financial Services',
    'Huntington Insurance**',
    'The Mahoney Group',
    'Rose & Kiernan Inc.',
    'Premier Group Insurance',
    'Fisher Brown Bottrell Insurance Inc.**',
    'Charles L. Crane Agency',
    'Robertson Ryan & Associates',
    'Rich & Cartmill Inc.',
    'Andreini & Company',
    'PCF Insurance Services LLC',
    'Haylor, Freyer & Coon Inc.',
    'People’s United Insurance Agency Inc.**',
    'James G Parker Insurance Associates',
    'Associated Benefits and Risk Consulting**',
    'Frost Insurance',
    'Bolton & Company',
    'M&T Insurance Agency Inc.**',
    'Sterling Seacrest Partners Inc.',
    'HNI',
    'TIS Insurance Sevices Inc.',
    'HomeServices Insurance',
    'Moreton & Company',
    'Wood Gutmann & Bogart Insurance Brokers',
    'TRICOR',
    'Turner Surety & Insurance Brokerage (TSIB)',
    'World Insurance Associates LLC',
    'The Buckner Company Inc.',
    'R&R Insurance Services',
    'Rogers & Gray Insurance',
    'Insgroup Inc.',
    'AHT Insurance',
    'SullivanCurtisMonroe Insurance Services LLC',
    'Sihle Insurance Group Inc.',
    'Cobbs Allen',
    'JGS Insurance',
    'Tompkins Insurance Agencies Inc.**',
    'Atlas Insurance Brokers LLC',
    'Crest Insurance Group LLC',
    'John M Glover Agency',
    'Christensen Group',
    'Foa & Son Corporation',
    'Swingle Collins & Associates',
    'Atlas Insurance Agency',
    'The Daniel and Henry Company',
    'L/P Insurance Services',
    'Murray Securus',
    'Associated Insurance Management LLC',
    'Lipscomb & Pitts Insurance',
    'MJ Insurance Inc.'
];
