module.exports = [
    'Dream Destinations Getaways',
    'Paradise Travel',
    'Beyond Borders Traveling Booking',
    'Right Flight Travel Co.',
    'Cruisers Seaside Travel',
    'Safe Travels Vacations',
    'First Class Corporate Travel',
    'Madison Ave. Travel Agent',
    'Travel Right',
    'Royalty Travel Systems',
    'Now Boarding Flight Organizers',
    'Speedy Getaways',
    'Willow Tree Travel & Resort',
    'Exploration Travel',
    'Pristine Vacation Planner',
    'I DO! Honeymoon Helpers',
    'Destination Anywhere',
    'Point B Travel Company',
    'Travelcations',
    'Smiles For Miles Travel Agent',
    'Sangria Tour & Cruise',
    'Where to Go Travel Tours',
    'Tropical Travel',
    'Business Class Travel Inc.',
    'Weekend Getaways',
    '4 Seasons Travel Company',
    'Sunset Vacations',
    'Whisked Away Travel',
    'Airborne Travel Agency',
    'Breathtaking Vacations',
    'N & L Travel International',
    'Rustic Woods Wilderness Expeditions',
    'Happy Trails Travel Company',
    'The Travel Connection',
    'Off Road Adventures Travel Company',
    'Tour Guide Travel Agency',
    'Mountain Top Travel Co.',
    'Jet Set Travel Services',
    'Hot Spot Travel Agency',
    'All American Vacation',
    'Oasis Travel',
    'World Wonders Travel Co.',
    'Great Vacations Travel Co.',
    'Fairytale Family Travel Agent',
    'See America RV Services',
    'Twin City Travel & Tourism',
    'Summer Vacations',
    'Swiss Family Beachfront Tours',
    'Cool River Travel Agency',
    'Peaceful Travel Planning',
    'Spirit of Adventure Travel Agent',
    'Seven Seas Travel Agent',
    'Miami Air & Sea Travel Agency',
    'Passports Travel Planners',
    'The Vacation Connection',
    'Happy Travels Vacations',
    'Pheonix Travel & Tour',
    'Sky High Travel',
    'International Adventures Travel',
    'On Time Travel Organizers',
    'Pirate Cove Travel Co.',
    'Wilderness Explorers',
    'World Wide Travel',
    'Up Up and Away Travel Agency',
    'Oh The Places You\'ll Go Travel Co.',
    'Holy Trinity Missions Trips',
    'Destination Vacation',
    'Homeward Holidays',
    'Coastline Corporate Travel Co.',
    'Smart Family Vacations',
    'Beyond the Sea Cruise Services',
    'Welcome Travel Agents',
    'Sky Blu Air & Sea',
    'Sea Turtle Travel & Tours',
    'Gateway Getaways',
    'Airwaves Flights & Cruises',
    'Sites & Sounds Tourism',
    'New Realm Travel',
    'Fly Away Travel Agent',
    'Wayward Travel Company',
    'Open Road RV Rental',
    'Mapstat Travel Agent',
    'Destiny Travel International',
    'Lido Travel & Cruise',
    'Howard Commercial Travel',
    'Global Getaways Inc.',
    'Columbus Business Travel Inc.',
    'Route 66 RVs',
    'Artic Waters Travel Agency',
    'National Pride Travel Planning',
    'Safari Travel Services',
    'Evergreen Travel Insurance',
    'Pegasus Private Travel Services',
    'Big City Sightseeing Tours',
    'Golden Ticket Guided Tours',
    'Mayflower Travel Agency',
    'Far Far Away Travel Agency',
    'Whitepeak Mountain Travel Guides',
    'Westshore Travel Corp.',
    'Triumph Travel Agency'
];
